language: cpp

compiler:
    -gcc
    -clang

env:
    global:
    - BUILD_RESTLESS_TESTS=ON

sudo: required

matrix:
  include:
    - compiler: gcc
      env: USE_SYSTEM_CMAKE=OFF


before_install:
    - sudo apt-get update

install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install g++-4.8 -y --force-yes
    - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - if [ "$USE_SYSTEM_CMAKE" == "OFF" ]; then sudo apt-get remove cmake && wget http://www.cmake.org/files/v3.2/cmake-3.2.1.tar.gz && tar -xzf cmake-3.2.1.tar.gz && cd cmake-3.2.1 && ./bootstrap > /dev/null && make -j8 > /dev/null && sudo make install && cd .. && rm -rf cmake-3.2.1 cmake-3.2.1.tar.gz; else sudo apt-get install -y cmake; fi
    - sudo apt-get install libcurl4-openssl-dev

before_script:
    - cmake --version
    - cd build
    - cmake ..

script:
    - make VERBOSE=1
    - make test
